### ISSUE TITLE
 Connection timed out

### ISSUE THREAD

**Issue by rdozinho** [meirelesff/deflateBR#8]
Fala, Fernando. Obrigado pelo pacote.

Quando tento rodar, tenho o erro de timout

`...

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [ipeadata.gov.br] Connection timed out after 10011 milliseconds`

Tentei mudar o timeout, alterei firewall e modifiquei o antivírus. Tem alguma ideia de como resolver?

**Comment by meirelesff** [comment]
Oi, @rdozinho, obrigado pelo retorno. Infelizmente, esse erro está sendo muito comum ultimamente e provavelmente (95% de certeza) tem a ver com o servidor do Ipea, que aparentemente está instável nos últimos dias -- em algum momento, até saiu do ar. Eu ainda estou esperando para ver se é o caso de pensar numa alternativa pra obter os dados necessários, mas isso também pode dar trabalho. Enfim, tomara que o problema se resolva sozinho.

**Comment by rdozinho** [comment]
@meirelesff bom saber que não é um problema aqui rs. Vou esperar um tempo e ver se volta ao normal, então.

Muito obrigado de qualquer forma!
